FROM mcr.microsoft.com/dotnet/sdk:10.0.300 AS migrator
WORKDIR /src

COPY Merconiq.sln .
COPY src/Merconiq.Web/Merconiq.Web.csproj src/Merconiq.Web/
COPY src/Merconiq.Core/Merconiq.Core.csproj src/Merconiq.Core/
COPY src/Merconiq.Infrastructure/Merconiq.Infrastructure.csproj src/Merconiq.Infrastructure/

RUN dotnet restore src/Merconiq.Web/Merconiq.Web.csproj
RUN dotnet tool install --global dotnet-ef --version 10.0.9
ENV PATH="/root/.dotnet/tools:${PATH}"

COPY . .

ENTRYPOINT ["dotnet", "ef", "database", "update", "--project", "src/Merconiq.Infrastructure", "--startup-project", "src/Merconiq.Web"]
