services:
  db:
    ports:
      - "${DB_PORT:-5432}:5432"

  app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5000:5000"
    volumes:
      - ./InventoryManagementSystem.Web:/src/InventoryManagementSystem.Web:ro
      - ./InventoryManagementSystem.Core:/src/InventoryManagementSystem.Core:ro
      - ./InventoryManagementSystem.Infrastructure:/src/InventoryManagementSystem.Infrastructure:ro
      - app-logs:/app/logs
    develop:
      watch:
        - action: rebuild
          path: ./InventoryManagementSystem.Web
        - action: rebuild
          path: ./InventoryManagementSystem.Core
        - action: rebuild
          path: ./InventoryManagementSystem.Infrastructure

volumes:
  app-logs:
    driver: local
