// <auto-generated />
using InventoryManagementSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace InventoryManagementSystem.Infrastructure.Migrations;

[DbContext(typeof(InventoryDbContext))]
[Migration("20260915100000_AddWebhookOutbox")]
partial class AddWebhookOutbox
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
    }
}
