// <auto-generated />
using Merconiq.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Merconiq.Infrastructure.Migrations;

[DbContext(typeof(InventoryDbContext))]
[Migration("20260917010000_AddItemExternalId")]
partial class AddItemExternalId
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
}
